title: Suspicious Remote AppX Package Locations
id: 8b48ad89-10d8-4382-a546-50588c410f0d
status: experimental
description: Detects an appx package added the pipeline of the "to be processed" packages which is downloaded from a suspicious domain
references:
    - Internal Research
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
    - https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
    - https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/01/11
modified: 2023/01/19
tags:
    - attack.defense_evasion
logsource:
    product: windows
    service: appxdeployment-server
detection:
    selection:
        EventID: 854
        Path|contains:
            - 'transfer.sh'
            - 'raw.githubusercontent.com'
            - 'gist.githubusercontent.com'
            - 'pastebin.com'
            - 'cdn.discordapp.com/attachments/'
            - 'mediafire.com'
            - 'mega.nz'
            - 'ddns.net'
            - '.paste.ee'
            - '.hastebin.com'
            - '.ghostbin.co/'
            - 'ufile.io'
            - 'storage.googleapis.com'
            - 'anonfiles.com'
            - 'send.exploit.in'
            - 'privatlab.net'
            - 'privatlab.com'
            - 'sendspace.com'
            - 'pastetext.net'
            - 'pastebin.pl'
            - 'paste.ee'
    condition: selection
falsepositives:
    - Unknown
level: high
