title: Sysmon Crash
id: 4d7f1827-1637-4def-8d8a-fd254f9454df
status: experimental
description: Detects application popup reporting a failure of the Sysmon service
author: Tim Shelton
date: 2022/04/26
logsource:
  product: windows
  service: system
detection:
  selection:
    Provider_Name: 'Application Popup'
    EventID: 26
    Caption: 'sysmon64.exe - Application Error'
  condition: selection
falsepositives:
  - Unknown
level: high
tags:
  - attack.t1562
  - attack.impair_defenses
