title: Elastic Common Schema mapping for proxy logs
order: 20
backends:
  - es-qs
  - es-dsl
  - kibana
  - xpack-watcher
  - elastalert
  - elastalert-dsl
logsources:
  proxy:
    category: proxy
    index: filebeat-*
fieldmappings:
  c-uri: url.original
  c-uri-extension: url.extension
  c-uri-query: url.query
  c-uri-stem: url.original
  c-useragent: user_agent.original
  cs-cookie: http.cookie
  cs-host: url.domain
  cs-method: http.request.method
  r-dns: url.domain
  sc-status: http.response.status_code
