logsources:
    apache:
        category: webserver
        index: logstash-apache-*
    webapp-error:
        category: application
        index: logstash-apache_error-*
    linux-auth:
        product: linux
        service: auth
        index: logstash-auth-*
fieldmappings:
    client_ip: clientip
    url: request
defaultindex: logstash-*
