title: Logstash Windows common log sources
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - kibana
  - kibana-ndjson
  - xpack-watcher
  - elastalert
  - elastalert-dsl
  - ee-outliers
logsources:
  windows:
    product: windows
    index: logstash-windows-*
  windows-application:
    product: windows
    service: application
    conditions:
      Channel: Application
  windows-security:
    product: windows
    service: security
    conditions:
      Channel: Security
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      Channel: Microsoft-Windows-Sysmon
  windows-dns-server:
    product: windows
    service: dns-server
    conditions:
      Channel: 'DNS Server'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      Channel: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
  windows-dhcp:
    product: windows
    service: dhcp
    conditions:
      Channel: 'Microsoft-Windows-DHCP-Server/Operational'
  windows-defender:
    product: windows
    service: windefend
    conditions:
      Channel: 'Microsoft-Windows-Windows Defender/Operational'
  windows-ntlm:
    product: windows
    service: ntlm
    conditions:
      Channel: 'Microsoft-Windows-NTLM/Operational'
  windows-applocker:
    product: windows
    service: applocker
    conditions:
      Channel:
        - 'Microsoft-Windows-AppLocker/MSI and Script'
        - 'Microsoft-Windows-AppLocker/EXE and DLL'
        - 'Microsoft-Windows-AppLocker/Packaged app-Deployment'
        - 'Microsoft-Windows-AppLocker/Packaged app-Execution'
  windows-msexchange-management:
    product: windows
    service: msexchange-management
    conditions:
      Channel: 'MSExchange Management'
  windows-printservice-admin:
    product: windows
    service: printservice-admin
    conditions:
      Channel: 'Microsoft-Windows-PrintService/Admin'
  windows-printservice-operational:
    product: windows
    service: printservice-operational
    conditions:
      Channel: 'Microsoft-Windows-PrintService/Operational'
  windows-terminalservices-localsessionmanager-operational:
    product: windows
    service: terminalservices-localsessionmanager
    conditions:
      Channel: 'Microsoft-Windows-TerminalServices-LocalSessionManager/Operational'
  windows-codeintegrity-operational:
    product: windows
    service: codeintegrity-operational
    conditions:
      Channel: 'Microsoft-Windows-CodeIntegrity/Operational'
  windows-smbclient-security:
    product: windows
    service: smbclient-security
    conditions:
      Channel: 'Microsoft-Windows-SmbClient/Security'
  windows-firewall-advanced-security:
    product: windows
    service: firewall-as
    conditions:
      Channel: 'Microsoft-Windows-Windows Firewall With Advanced Security/Firewall'
  windows-bits-client:
    product: windows
    service: bits-client
    conditions:
      Channel: 'Microsoft-Windows-Bits-Client/Operational'
  windows-security-mitigations:
    product: windows
    service: security-mitigations
    conditions:
      Channel:
        - 'Microsoft-Windows-Security-Mitigations/Kernel Mode'
        - 'Microsoft-Windows-Security-Mitigations/User Mode'
  windows-diagnosis:
    product: windows
    service: diagnosis-scripted
    conditions:
      Channel: 'Microsoft-Windows-Diagnosis-Scripted/Operational'
  windows-shell-core:
    product: windows
    service: shell-core
    conditions:
      Channel: 'Microsoft-Windows-Shell-Core/Operational'
  windows-openssh:
    product: windows
    service: openssh
    conditions:
      Channel: 'OpenSSH/Operational'
  windows-ldap-debug:
    product: windows
    service: ldap_debug
    conditions:
      Channel: 'Microsoft-Windows-LDAP-Client/Debug'
  windows-bitlocker:
    product: windows
    service: bitlocker
    conditions:
      Channel: 'Microsoft-Windows-BitLocker/BitLocker Management'
defaultindex: logstash-*
