name: Update Sigma Rules
on:
  schedule:
    - cron:  "0 * * * *"

jobs:
  update:
    name: Update Upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rule Branch
        uses: actions/checkout@e8bd1dffb6451bb0d84dbcd3ed059daca1371180
        with:
          ref: source
          token: ${{ github.token }}
      - name: Status
        run: git status && git branch && git remote
      - name: Set Git Ident
        run: git config --global user.email "ops@limacharlie.io"; git config --global user.name "LimaCharlie Ops"
      - name: Set Upstream
        run: git remote add upstream https://github.com/Neo23x0/sigma.git && git fetch upstream
      - name: Merge
        run: git merge upstream/master
      - name: Status
        run: git status && git branch && git remote
      - name: Commit
        run: git push -f