title: Monitor WMI "Win32_Process::Create" command execution by Office Applications.
description: Initial execution of malicious document calls wmic to execute the file with regsvr32
references:
- https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
- https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
author: "Idea by: Vadim Khrykov"
tags:
- attack.t1204.002
- attack.t1047
- attack.t1218.010
- attack.execution
- attack.defence_evasion
status: experimental
Date: 2021/23/8
logsource:
  product: EndPoint Detection Logs
  category: process_creation
detection:
  description: Add more office applications to the rule logic of choice
  selection1:
    EventLog: EDR
    EventType: WMIExecution
    WMIcommand: '*Win32_Process\:\:Create*'
  selection2:
    - Image:
      - '*\winword.exe'
      - '*\excel.exe'
      - '*\powerpnt.exe'
  condition: selection1 AND selection2
falsepositives:
- ""
level: high