title: WMI Uninstall An Application
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
status: experimental
description: Uninstall an application with wmic
author: frac113
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
date: 2022/01/28
modified: 2022/05/13
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - Image|endswith: '\WMIC.exe'
        - OriginalFileName: 'wmic.exe'
    selection_cli:
        CommandLine|contains: 'call uninstall'
    condition: all of selection*
falsepositives:
    - Unknown
level: medium
tags:
    - attack.execution
    - attack.t1047
